// <auto-generated />
using System;
using DevelopersTeam.Fruitlogix.Platform.Shared.Infrastructure.Persistence.EFC.Configuration;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DevelopersTeam.Fruitlogix.Platform.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("DevelopersTeam.Fruitlogix.Platform.IoTInfrastructure.Domain.Model.Aggregates.AlertRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("AlertMessage")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("alert_message");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<string>("DeviceType")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("device_type");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("severity");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_alert_rules");

                    b.ToTable("alert_rules");
                });

            modelBuilder.Entity("DevelopersTeam.Fruitlogix.Platform.IoTInfrastructure.Domain.Model.Aggregates.IoTDevice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<string>("DeviceType")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("device_type");

                    b.Property<DateTimeOffset?>("LastReadingAt")
                        .HasColumnType("datetime")
                        .HasColumnName("last_reading_at");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("location");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_io_t_devices");

                    b.ToTable("io_t_devices");
                });

            modelBuilder.Entity("DevelopersTeam.Fruitlogix.Platform.IoTInfrastructure.Domain.Model.Aggregates.SensorReading", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<int>("DeviceId")
                        .HasColumnType("int")
                        .HasColumnName("device_id");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("datetime")
                        .HasColumnName("timestamp");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_sensor_readings");

                    b.ToTable("sensor_readings");
                });

            modelBuilder.Entity("DevelopersTeam.Fruitlogix.Platform.Logistics.Domain.Model.Aggregates.Alert", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<int>("DeliveryId")
                        .HasColumnType("int")
                        .HasColumnName("delivery_id");

                    b.Property<bool>("IsResolved")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_resolved");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("message");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("severity");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_alerts");

                    b.ToTable("alerts");
                });

            modelBuilder.Entity("DevelopersTeam.Fruitlogix.Platform.Logistics.Domain.Model.Aggregates.Delivery", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<string>("CurrentStatus")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("current_status");

                    b.Property<string>("DelayReason")
                        .HasColumnType("longtext")
                        .HasColumnName("delay_reason");

                    b.Property<DateTime>("EstimatedTimeOfArrival")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("estimated_time_of_arrival");

                    b.Property<int>("OrderId")
                        .HasColumnType("int")
                        .HasColumnName("order_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_deliveries");

                    b.ToTable("deliveries");
                });

            modelBuilder.Entity("DevelopersTeam.Fruitlogix.Platform.Logistics.Domain.Model.Entities.TrackingLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<int>("DeliveryId")
                        .HasColumnType("int")
                        .HasColumnName("delivery_id");

                    b.Property<double>("Humidity")
                        .HasColumnType("double")
                        .HasColumnName("humidity");

                    b.Property<double>("Temperature")
                        .HasColumnType("double")
                        .HasColumnName("temperature");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("timestamp");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_tracking_logs");

                    b.ToTable("tracking_logs");
                });

            modelBuilder.Entity("DevelopersTeam.Fruitlogix.Platform.Messaging.Domain.Model.Aggregates.Conversation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<int>("OrderId")
                        .HasColumnType("int")
                        .HasColumnName("order_id");

                    b.Property<int>("ParticipantAId")
                        .HasColumnType("int")
                        .HasColumnName("participant_a_id");

                    b.Property<int>("ParticipantBId")
                        .HasColumnType("int")
                        .HasColumnName("participant_b_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_conversations");

                    b.ToTable("conversations");
                });

            modelBuilder.Entity("DevelopersTeam.Fruitlogix.Platform.Messaging.Domain.Model.Entities.Message", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int?>("ConversationId")
                        .HasColumnType("int")
                        .HasColumnName("conversation_id");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<int>("SenderId")
                        .HasColumnType("int")
                        .HasColumnName("sender_id");

                    b.Property<DateTimeOffset>("SentAt")
                        .HasColumnType("datetime")
                        .HasColumnName("sent_at");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_messages");

                    b.HasIndex("ConversationId")
                        .HasDatabaseName("i_x_messages_conversation_id");

                    b.ToTable("messages");
                });

            modelBuilder.Entity("DevelopersTeam.Fruitlogix.Platform.OrderManagement.Domain.Model.Aggregates.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("CancellationReason")
                        .HasColumnType("longtext")
                        .HasColumnName("cancellation_reason");

                    b.Property<int>("CommercialClientId")
                        .HasColumnType("int")
                        .HasColumnName("commercial_client_id");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<DateOnly>("DeliveryDueDate")
                        .HasColumnType("date")
                        .HasColumnName("delivery_due_date");

                    b.Property<string>("FruitType")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("fruit_type");

                    b.Property<string>("Notes")
                        .HasColumnType("longtext")
                        .HasColumnName("notes");

                    b.Property<int?>("ProducerId")
                        .HasColumnType("int")
                        .HasColumnName("producer_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("status");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("total_amount");

                    b.Property<double>("TotalVolume")
                        .HasColumnType("double")
                        .HasColumnName("total_volume");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_orders");

                    b.ToTable("orders");
                });

            modelBuilder.Entity("DevelopersTeam.Fruitlogix.Platform.OrderManagement.Domain.Model.Entities.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<string>("FruitName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("fruit_name");

                    b.Property<int?>("OrderId")
                        .HasColumnType("int")
                        .HasColumnName("order_id");

                    b.Property<double>("QuantityKg")
                        .HasColumnType("double")
                        .HasColumnName("quantity_kg");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("unit_price");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_order_items");

                    b.HasIndex("OrderId")
                        .HasDatabaseName("i_x_order_items_order_id");

                    b.ToTable("order_items");
                });

            modelBuilder.Entity("DevelopersTeam.Fruitlogix.Platform.PaymentManagement.Domain.Model.Aggregates.Invoice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int>("ClientId")
                        .HasColumnType("int")
                        .HasColumnName("client_id");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<DateOnly>("DueDate")
                        .HasColumnType("date")
                        .HasColumnName("due_date");

                    b.Property<string>("InvoiceType")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("invoice_type");

                    b.Property<DateTimeOffset?>("IssuedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("issued_at");

                    b.Property<int?>("OrderId")
                        .HasColumnType("int")
                        .HasColumnName("order_id");

                    b.Property<DateTimeOffset?>("PaidAt")
                        .HasColumnType("datetime")
                        .HasColumnName("paid_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_invoices");

                    b.ToTable("invoices");
                });

            modelBuilder.Entity("DevelopersTeam.Fruitlogix.Platform.PaymentManagement.Domain.Model.Aggregates.PaymentTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<string>("Gateway")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("gateway");

                    b.Property<string>("GatewayRef")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("gateway_ref");

                    b.Property<int>("InvoiceId")
                        .HasColumnType("int")
                        .HasColumnName("invoice_id");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("method");

                    b.Property<DateTimeOffset>("ProcessedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("processed_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_payment_transactions");

                    b.ToTable("payment_transactions");
                });

            modelBuilder.Entity("DevelopersTeam.Fruitlogix.Platform.Profiles.Domain.Model.Aggregates.Producer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Certifications")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("certifications");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("full_name");

                    b.Property<string>("LegalName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("legal_name");

                    b.Property<DateOnly?>("OperationsStartDate")
                        .HasColumnType("date")
                        .HasColumnName("operations_start_date");

                    b.Property<string>("Photo")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("photo");

                    b.Property<string>("ProducerType")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("producer_type");

                    b.Property<double>("Rating")
                        .HasColumnType("double")
                        .HasColumnName("rating");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_producers");

                    b.ToTable("producers");
                });

            modelBuilder.Entity("DevelopersTeam.Fruitlogix.Platform.QualityControl.Domain.Model.Aggregates.HarvestBatch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext")
                        .HasColumnName("created_by");

                    b.Property<string>("FruitType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("fruit_type");

                    b.Property<DateOnly>("HarvestDate")
                        .HasColumnType("date")
                        .HasColumnName("harvest_date");

                    b.Property<int>("ProducerId")
                        .HasColumnType("int")
                        .HasColumnName("producer_id");

                    b.Property<double>("QuantityKg")
                        .HasColumnType("double")
                        .HasColumnName("quantity_kg");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("longtext")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("p_k_harvest_batches");

                    b.ToTable("harvest_batches");
                });

            modelBuilder.Entity("DevelopersTeam.Fruitlogix.Platform.QualityControl.Domain.Model.Aggregates.Incident", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int>("BatchId")
                        .HasColumnType("int")
                        .HasColumnName("batch_id");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("description");

                    b.Property<string>("EvidenceUrls")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("evidence_urls");

                    b.Property<DateTimeOffset?>("ResolvedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("resolved_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("longtext")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("p_k_incidents");

                    b.ToTable("incidents");
                });

            modelBuilder.Entity("DevelopersTeam.Fruitlogix.Platform.QualityControl.Domain.Model.Aggregates.QualityInspection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int>("BatchId")
                        .HasColumnType("int")
                        .HasColumnName("batch_id");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext")
                        .HasColumnName("created_by");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("notes");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("longtext")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("p_k_quality_inspections");

                    b.ToTable("quality_inspections");
                });

            modelBuilder.Entity("DevelopersTeam.Fruitlogix.Platform.QualityControl.Domain.Model.Entities.PreparationChecklist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<bool>("CaliberSortingConfirmed")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("caliber_sorting_confirmed");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext")
                        .HasColumnName("created_by");

                    b.Property<bool>("DryCleaningDone")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("dry_cleaning_done");

                    b.Property<bool>("FinalBoxSealing")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("final_box_sealing");

                    b.Property<bool>("PackagingMaterialInspected")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("packaging_material_inspected");

                    b.Property<int>("QualityInspectionId")
                        .HasColumnType("int")
                        .HasColumnName("quality_inspection_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("longtext")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("p_k_preparation_checklists");

                    b.HasIndex("QualityInspectionId")
                        .IsUnique()
                        .HasDatabaseName("i_x_preparation_checklists_quality_inspection_id");

                    b.ToTable("preparation_checklists");
                });

            modelBuilder.Entity("DevelopersTeam.Fruitlogix.Platform.QualityControl.Domain.Model.Entities.TechnicalParameters", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<double>("BrixDegrees")
                        .HasColumnType("double")
                        .HasColumnName("brix_degrees");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext")
                        .HasColumnName("created_by");

                    b.Property<double>("HumidityPercent")
                        .HasColumnType("double")
                        .HasColumnName("humidity_percent");

                    b.Property<double>("Ph")
                        .HasColumnType("double")
                        .HasColumnName("ph");

                    b.Property<int>("QualityInspectionId")
                        .HasColumnType("int")
                        .HasColumnName("quality_inspection_id");

                    b.Property<double>("TemperatureCelsius")
                        .HasColumnType("double")
                        .HasColumnName("temperature_celsius");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("longtext")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("p_k_technical_parameters");

                    b.HasIndex("QualityInspectionId")
                        .IsUnique()
                        .HasDatabaseName("i_x_technical_parameters_quality_inspection_id");

                    b.ToTable("technical_parameters");
                });

            modelBuilder.Entity("DevelopersTeam.Fruitlogix.Platform.QualityControl.Domain.Model.Entities.VisualInspection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int>("AppearanceRating")
                        .HasColumnType("int")
                        .HasColumnName("appearance_rating");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext")
                        .HasColumnName("created_by");

                    b.Property<bool>("HasBruises")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("has_bruises");

                    b.Property<bool>("HasDeformations")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("has_deformations");

                    b.Property<bool>("HasRot")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("has_rot");

                    b.Property<bool>("HasStains")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("has_stains");

                    b.Property<int>("QualityInspectionId")
                        .HasColumnType("int")
                        .HasColumnName("quality_inspection_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("longtext")
                        .HasColumnName("updated_by");

                    b.Property<double>("WastePercentage")
                        .HasColumnType("double")
                        .HasColumnName("waste_percentage");

                    b.HasKey("Id")
                        .HasName("p_k_visual_inspections");

                    b.HasIndex("QualityInspectionId")
                        .IsUnique()
                        .HasDatabaseName("i_x_visual_inspections_quality_inspection_id");

                    b.ToTable("visual_inspections");
                });

            modelBuilder.Entity("DevelopersTeam.Fruitlogix.Platform.IoTInfrastructure.Domain.Model.Aggregates.AlertRule", b =>
                {
                    b.OwnsOne("DevelopersTeam.Fruitlogix.Platform.IoTInfrastructure.Domain.Model.ValueObjects.ThresholdRange", "Threshold", b1 =>
                        {
                            b1.Property<int>("Id")
                                .HasColumnType("int")
                                .HasColumnName("id");

                            b1.Property<double>("Max")
                                .HasColumnType("double")
                                .HasColumnName("max_threshold");

                            b1.Property<double>("Min")
                                .HasColumnType("double")
                                .HasColumnName("min_threshold");

                            b1.HasKey("Id")
                                .HasName("p_k_alert_rules");

                            b1.ToTable("alert_rules");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("f_k_alert_rules_alert_rules_id");
                        });

                    b.Navigation("Threshold")
                        .IsRequired();
                });

            modelBuilder.Entity("DevelopersTeam.Fruitlogix.Platform.IoTInfrastructure.Domain.Model.Aggregates.IoTDevice", b =>
                {
                    b.OwnsOne("DevelopersTeam.Fruitlogix.Platform.IoTInfrastructure.Domain.Model.ValueObjects.DeviceCode", "DeviceCode", b1 =>
                        {
                            b1.Property<int>("Id")
                                .HasColumnType("int")
                                .HasColumnName("id");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("longtext")
                                .HasColumnName("device_code");

                            b1.HasKey("Id")
                                .HasName("p_k_io_t_devices");

                            b1.ToTable("io_t_devices");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("f_k_io_t_devices_io_t_devices_id");
                        });

                    b.Navigation("DeviceCode")
                        .IsRequired();
                });

            modelBuilder.Entity("DevelopersTeam.Fruitlogix.Platform.IoTInfrastructure.Domain.Model.Aggregates.SensorReading", b =>
                {
                    b.OwnsOne("DevelopersTeam.Fruitlogix.Platform.IoTInfrastructure.Domain.Model.ValueObjects.ReadingValue", "Reading", b1 =>
                        {
                            b1.Property<int>("Id")
                                .HasColumnType("int")
                                .HasColumnName("id");

                            b1.Property<string>("Unit")
                                .IsRequired()
                                .HasColumnType("longtext")
                                .HasColumnName("unit");

                            b1.Property<double>("Value")
                                .HasColumnType("double")
                                .HasColumnName("value");

                            b1.HasKey("Id")
                                .HasName("p_k_sensor_readings");

                            b1.ToTable("sensor_readings");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("f_k_sensor_readings_sensor_readings_id");
                        });

                    b.Navigation("Reading")
                        .IsRequired();
                });

            modelBuilder.Entity("DevelopersTeam.Fruitlogix.Platform.Logistics.Domain.Model.Aggregates.Delivery", b =>
                {
                    b.OwnsOne("DevelopersTeam.Fruitlogix.Platform.Logistics.Domain.Model.ValueObjects.DriverInfo", "Driver", b1 =>
                        {
                            b1.Property<int>("Id")
                                .HasColumnType("int")
                                .HasColumnName("id");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("longtext")
                                .HasColumnName("driver_name");

                            b1.Property<string>("Phone")
                                .IsRequired()
                                .HasColumnType("longtext")
                                .HasColumnName("driver_phone");

                            b1.HasKey("Id")
                                .HasName("p_k_deliveries");

                            b1.ToTable("deliveries");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("f_k_deliveries_deliveries_id");
                        });

                    b.OwnsOne("DevelopersTeam.Fruitlogix.Platform.Logistics.Domain.Model.ValueObjects.RouteInfo", "Route", b1 =>
                        {
                            b1.Property<int>("Id")
                                .HasColumnType("int")
                                .HasColumnName("id");

                            b1.Property<string>("Destination")
                                .IsRequired()
                                .HasColumnType("longtext")
                                .HasColumnName("route_destination");

                            b1.Property<double>("DistanceKm")
                                .HasColumnType("double")
                                .HasColumnName("route_distance_km");

                            b1.Property<string>("Origin")
                                .IsRequired()
                                .HasColumnType("longtext")
                                .HasColumnName("route_origin");

                            b1.HasKey("Id")
                                .HasName("p_k_deliveries");

                            b1.ToTable("deliveries");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("f_k_deliveries_deliveries_id");
                        });

                    b.OwnsOne("DevelopersTeam.Fruitlogix.Platform.Logistics.Domain.Model.ValueObjects.VehicleInfo", "Vehicle", b1 =>
                        {
                            b1.Property<int>("Id")
                                .HasColumnType("int")
                                .HasColumnName("id");

                            b1.Property<string>("Plate")
                                .IsRequired()
                                .HasColumnType("longtext")
                                .HasColumnName("vehicle_plate");

                            b1.Property<string>("Type")
                                .IsRequired()
                                .HasColumnType("longtext")
                                .HasColumnName("vehicle_type");

                            b1.HasKey("Id")
                                .HasName("p_k_deliveries");

                            b1.ToTable("deliveries");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("f_k_deliveries_deliveries_id");
                        });

                    b.Navigation("Driver")
                        .IsRequired();

                    b.Navigation("Route")
                        .IsRequired();

                    b.Navigation("Vehicle")
                        .IsRequired();
                });

            modelBuilder.Entity("DevelopersTeam.Fruitlogix.Platform.Logistics.Domain.Model.Entities.TrackingLog", b =>
                {
                    b.OwnsOne("DevelopersTeam.Fruitlogix.Platform.Logistics.Domain.Model.ValueObjects.GpsCoordinates", "Location", b1 =>
                        {
                            b1.Property<int>("Id")
                                .HasColumnType("int")
                                .HasColumnName("id");

                            b1.Property<double>("Latitude")
                                .HasColumnType("double")
                                .HasColumnName("latitude");

                            b1.Property<double>("Longitude")
                                .HasColumnType("double")
                                .HasColumnName("longitude");

                            b1.HasKey("Id")
                                .HasName("p_k_tracking_logs");

                            b1.ToTable("tracking_logs");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("f_k_tracking_logs_tracking_logs_id");
                        });

                    b.Navigation("Location")
                        .IsRequired();
                });

            modelBuilder.Entity("DevelopersTeam.Fruitlogix.Platform.Messaging.Domain.Model.Entities.Message", b =>
                {
                    b.HasOne("DevelopersTeam.Fruitlogix.Platform.Messaging.Domain.Model.Aggregates.Conversation", null)
                        .WithMany("Messages")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("f_k_messages_conversations_conversation_id");

                    b.OwnsOne("DevelopersTeam.Fruitlogix.Platform.Messaging.Domain.Model.ValueObjects.MessageContent", "Content", b1 =>
                        {
                            b1.Property<int>("Id")
                                .HasColumnType("int")
                                .HasColumnName("id");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("longtext")
                                .HasColumnName("content");

                            b1.HasKey("Id")
                                .HasName("p_k_messages");

                            b1.ToTable("messages");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("f_k_messages_messages_id");
                        });

                    b.Navigation("Content")
                        .IsRequired();
                });

            modelBuilder.Entity("DevelopersTeam.Fruitlogix.Platform.OrderManagement.Domain.Model.Entities.OrderItem", b =>
                {
                    b.HasOne("DevelopersTeam.Fruitlogix.Platform.OrderManagement.Domain.Model.Aggregates.Order", null)
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("f_k_order_items_orders_order_id");
                });

            modelBuilder.Entity("DevelopersTeam.Fruitlogix.Platform.PaymentManagement.Domain.Model.Aggregates.Invoice", b =>
                {
                    b.OwnsOne("DevelopersTeam.Fruitlogix.Platform.PaymentManagement.Domain.Model.ValueObjects.Money", "TotalAmount", b1 =>
                        {
                            b1.Property<int>("Id")
                                .HasColumnType("int")
                                .HasColumnName("id");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("total_amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("varchar(3)")
                                .HasColumnName("currency");

                            b1.HasKey("Id")
                                .HasName("p_k_invoices");

                            b1.ToTable("invoices");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("f_k_invoices_invoices_id");
                        });

                    b.Navigation("TotalAmount")
                        .IsRequired();
                });

            modelBuilder.Entity("DevelopersTeam.Fruitlogix.Platform.PaymentManagement.Domain.Model.Aggregates.PaymentTransaction", b =>
                {
                    b.OwnsOne("DevelopersTeam.Fruitlogix.Platform.PaymentManagement.Domain.Model.ValueObjects.Money", "Amount", b1 =>
                        {
                            b1.Property<int>("Id")
                                .HasColumnType("int")
                                .HasColumnName("id");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("varchar(3)")
                                .HasColumnName("currency");

                            b1.HasKey("Id")
                                .HasName("p_k_payment_transactions");

                            b1.ToTable("payment_transactions");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("f_k_payment_transactions_payment_transactions_id");
                        });

                    b.OwnsOne("DevelopersTeam.Fruitlogix.Platform.PaymentManagement.Domain.Model.ValueObjects.CardDetails", "CardDetails", b1 =>
                        {
                            b1.Property<int>("Id")
                                .HasColumnType("int")
                                .HasColumnName("id");

                            b1.Property<string>("CardBrand")
                                .HasMaxLength(20)
                                .HasColumnType("varchar(20)")
                                .HasColumnName("card_brand");

                            b1.Property<string>("CardEnding")
                                .HasMaxLength(4)
                                .HasColumnType("varchar(4)")
                                .HasColumnName("card_ending");

                            b1.HasKey("Id")
                                .HasName("p_k_payment_transactions");

                            b1.ToTable("payment_transactions");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("f_k_payment_transactions_payment_transactions_id");
                        });

                    b.Navigation("Amount")
                        .IsRequired();

                    b.Navigation("CardDetails");
                });

            modelBuilder.Entity("DevelopersTeam.Fruitlogix.Platform.Profiles.Domain.Model.Aggregates.Producer", b =>
                {
                    b.OwnsOne("DevelopersTeam.Fruitlogix.Platform.Profiles.Domain.Model.ValueObjects.ContactInfo", "ContactInfo", b1 =>
                        {
                            b1.Property<int>("Id")
                                .HasColumnType("int")
                                .HasColumnName("id");

                            b1.Property<string>("Email")
                                .IsRequired()
                                .HasColumnType("longtext")
                                .HasColumnName("email");

                            b1.Property<string>("Phone")
                                .IsRequired()
                                .HasColumnType("longtext")
                                .HasColumnName("phone");

                            b1.HasKey("Id")
                                .HasName("p_k_producers");

                            b1.ToTable("producers");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("f_k_producers_producers_id");
                        });

                    b.OwnsOne("DevelopersTeam.Fruitlogix.Platform.Profiles.Domain.Model.ValueObjects.Location", "Location", b1 =>
                        {
                            b1.Property<int>("Id")
                                .HasColumnType("int")
                                .HasColumnName("id");

                            b1.Property<string>("Address")
                                .IsRequired()
                                .HasColumnType("longtext")
                                .HasColumnName("address");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasColumnType("longtext")
                                .HasColumnName("city");

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasColumnType("longtext")
                                .HasColumnName("country");

                            b1.Property<string>("Region")
                                .IsRequired()
                                .HasColumnType("longtext")
                                .HasColumnName("region");

                            b1.HasKey("Id")
                                .HasName("p_k_producers");

                            b1.ToTable("producers");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("f_k_producers_producers_id");
                        });

                    b.OwnsOne("DevelopersTeam.Fruitlogix.Platform.Profiles.Domain.Model.ValueObjects.ProductionInfo", "ProductionInfo", b1 =>
                        {
                            b1.Property<int>("Id")
                                .HasColumnType("int")
                                .HasColumnName("id");

                            b1.Property<string>("Crop")
                                .IsRequired()
                                .HasColumnType("longtext")
                                .HasColumnName("crop");

                            b1.Property<double>("CultivatedHectares")
                                .HasColumnType("double")
                                .HasColumnName("cultivated_hectares");

                            b1.Property<string>("MonthlyProduction")
                                .IsRequired()
                                .HasColumnType("longtext")
                                .HasColumnName("monthly_production");

                            b1.HasKey("Id")
                                .HasName("p_k_producers");

                            b1.ToTable("producers");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("f_k_producers_producers_id");
                        });

                    b.OwnsOne("DevelopersTeam.Fruitlogix.Platform.Profiles.Domain.Model.ValueObjects.TaxId", "TaxId", b1 =>
                        {
                            b1.Property<int>("Id")
                                .HasColumnType("int")
                                .HasColumnName("id");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("longtext")
                                .HasColumnName("tax_id");

                            b1.HasKey("Id")
                                .HasName("p_k_producers");

                            b1.ToTable("producers");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("f_k_producers_producers_id");
                        });

                    b.Navigation("ContactInfo")
                        .IsRequired();

                    b.Navigation("Location")
                        .IsRequired();

                    b.Navigation("ProductionInfo")
                        .IsRequired();

                    b.Navigation("TaxId")
                        .IsRequired();
                });

            modelBuilder.Entity("DevelopersTeam.Fruitlogix.Platform.QualityControl.Domain.Model.Entities.PreparationChecklist", b =>
                {
                    b.HasOne("DevelopersTeam.Fruitlogix.Platform.QualityControl.Domain.Model.Aggregates.QualityInspection", null)
                        .WithOne("PreparationChecklist")
                        .HasForeignKey("DevelopersTeam.Fruitlogix.Platform.QualityControl.Domain.Model.Entities.PreparationChecklist", "QualityInspectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_quality_inspections_preparation");
                });

            modelBuilder.Entity("DevelopersTeam.Fruitlogix.Platform.QualityControl.Domain.Model.Entities.TechnicalParameters", b =>
                {
                    b.HasOne("DevelopersTeam.Fruitlogix.Platform.QualityControl.Domain.Model.Aggregates.QualityInspection", null)
                        .WithOne("TechnicalParameters")
                        .HasForeignKey("DevelopersTeam.Fruitlogix.Platform.QualityControl.Domain.Model.Entities.TechnicalParameters", "QualityInspectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_quality_inspections_technical");
                });

            modelBuilder.Entity("DevelopersTeam.Fruitlogix.Platform.QualityControl.Domain.Model.Entities.VisualInspection", b =>
                {
                    b.HasOne("DevelopersTeam.Fruitlogix.Platform.QualityControl.Domain.Model.Aggregates.QualityInspection", null)
                        .WithOne("VisualInspection")
                        .HasForeignKey("DevelopersTeam.Fruitlogix.Platform.QualityControl.Domain.Model.Entities.VisualInspection", "QualityInspectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_quality_inspections_visual");
                });

            modelBuilder.Entity("DevelopersTeam.Fruitlogix.Platform.Messaging.Domain.Model.Aggregates.Conversation", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("DevelopersTeam.Fruitlogix.Platform.OrderManagement.Domain.Model.Aggregates.Order", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("DevelopersTeam.Fruitlogix.Platform.QualityControl.Domain.Model.Aggregates.QualityInspection", b =>
                {
                    b.Navigation("PreparationChecklist")
                        .IsRequired();

                    b.Navigation("TechnicalParameters")
                        .IsRequired();

                    b.Navigation("VisualInspection")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
