// <auto-generated />
using System;
using DevelopersTeam.Fruitlogix.Platform.Shared.Infrastructure.Persistence.EFC.Configuration;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DevelopersTeam.Fruitlogix.Platform.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("DevelopersTeam.Fruitlogix.Platform.OrderManagement.Domain.Model.Aggregates.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("CancellationReason")
                        .HasColumnType("longtext")
                        .HasColumnName("cancellation_reason");

                    b.Property<int>("CommercialClientId")
                        .HasColumnType("int")
                        .HasColumnName("commercial_client_id");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<DateOnly>("DeliveryDueDate")
                        .HasColumnType("date")
                        .HasColumnName("delivery_due_date");

                    b.Property<string>("FruitType")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("fruit_type");

                    b.Property<string>("Notes")
                        .HasColumnType("longtext")
                        .HasColumnName("notes");

                    b.Property<int?>("ProducerId")
                        .HasColumnType("int")
                        .HasColumnName("producer_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("status");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("total_amount");

                    b.Property<double>("TotalVolume")
                        .HasColumnType("double")
                        .HasColumnName("total_volume");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_orders");

                    b.ToTable("orders");
                });

            modelBuilder.Entity("DevelopersTeam.Fruitlogix.Platform.OrderManagement.Domain.Model.Entities.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<string>("FruitName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("fruit_name");

                    b.Property<int?>("OrderId")
                        .HasColumnType("int")
                        .HasColumnName("order_id");

                    b.Property<double>("QuantityKg")
                        .HasColumnType("double")
                        .HasColumnName("quantity_kg");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("unit_price");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_order_items");

                    b.HasIndex("OrderId")
                        .HasDatabaseName("i_x_order_items_order_id");

                    b.ToTable("order_items");
                });

            modelBuilder.Entity("DevelopersTeam.Fruitlogix.Platform.Profiles.Domain.Model.Aggregates.Producer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Certifications")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("certifications");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("full_name");

                    b.Property<string>("LegalName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("legal_name");

                    b.Property<DateOnly?>("OperationsStartDate")
                        .HasColumnType("date")
                        .HasColumnName("operations_start_date");

                    b.Property<string>("Photo")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("photo");

                    b.Property<string>("ProducerType")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("producer_type");

                    b.Property<double>("Rating")
                        .HasColumnType("double")
                        .HasColumnName("rating");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_producers");

                    b.ToTable("producers");
                });

            modelBuilder.Entity("DevelopersTeam.Fruitlogix.Platform.QualityControl.Domain.Model.Aggregates.HarvestBatch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext")
                        .HasColumnName("created_by");

                    b.Property<string>("FruitType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("fruit_type");

                    b.Property<DateOnly>("HarvestDate")
                        .HasColumnType("date")
                        .HasColumnName("harvest_date");

                    b.Property<int>("ProducerId")
                        .HasColumnType("int")
                        .HasColumnName("producer_id");

                    b.Property<double>("QuantityKg")
                        .HasColumnType("double")
                        .HasColumnName("quantity_kg");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("longtext")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("p_k_harvest_batches");

                    b.ToTable("harvest_batches");
                });

            modelBuilder.Entity("DevelopersTeam.Fruitlogix.Platform.OrderManagement.Domain.Model.Entities.OrderItem", b =>
                {
                    b.HasOne("DevelopersTeam.Fruitlogix.Platform.OrderManagement.Domain.Model.Aggregates.Order", null)
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("f_k_order_items_orders_order_id");
                });

            modelBuilder.Entity("DevelopersTeam.Fruitlogix.Platform.Profiles.Domain.Model.Aggregates.Producer", b =>
                {
                    b.OwnsOne("DevelopersTeam.Fruitlogix.Platform.Profiles.Domain.Model.ValueObjects.ContactInfo", "ContactInfo", b1 =>
                        {
                            b1.Property<int>("Id")
                                .HasColumnType("int")
                                .HasColumnName("id");

                            b1.Property<string>("Email")
                                .IsRequired()
                                .HasColumnType("longtext")
                                .HasColumnName("email");

                            b1.Property<string>("Phone")
                                .IsRequired()
                                .HasColumnType("longtext")
                                .HasColumnName("phone");

                            b1.HasKey("Id")
                                .HasName("p_k_producers");

                            b1.ToTable("producers");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("f_k_producers_producers_id");
                        });

                    b.OwnsOne("DevelopersTeam.Fruitlogix.Platform.Profiles.Domain.Model.ValueObjects.Location", "Location", b1 =>
                        {
                            b1.Property<int>("Id")
                                .HasColumnType("int")
                                .HasColumnName("id");

                            b1.Property<string>("Address")
                                .IsRequired()
                                .HasColumnType("longtext")
                                .HasColumnName("address");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasColumnType("longtext")
                                .HasColumnName("city");

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasColumnType("longtext")
                                .HasColumnName("country");

                            b1.Property<string>("Region")
                                .IsRequired()
                                .HasColumnType("longtext")
                                .HasColumnName("region");

                            b1.HasKey("Id")
                                .HasName("p_k_producers");

                            b1.ToTable("producers");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("f_k_producers_producers_id");
                        });

                    b.OwnsOne("DevelopersTeam.Fruitlogix.Platform.Profiles.Domain.Model.ValueObjects.ProductionInfo", "ProductionInfo", b1 =>
                        {
                            b1.Property<int>("Id")
                                .HasColumnType("int")
                                .HasColumnName("id");

                            b1.Property<string>("Crop")
                                .IsRequired()
                                .HasColumnType("longtext")
                                .HasColumnName("crop");

                            b1.Property<double>("CultivatedHectares")
                                .HasColumnType("double")
                                .HasColumnName("cultivated_hectares");

                            b1.Property<string>("MonthlyProduction")
                                .IsRequired()
                                .HasColumnType("longtext")
                                .HasColumnName("monthly_production");

                            b1.HasKey("Id")
                                .HasName("p_k_producers");

                            b1.ToTable("producers");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("f_k_producers_producers_id");
                        });

                    b.OwnsOne("DevelopersTeam.Fruitlogix.Platform.Profiles.Domain.Model.ValueObjects.TaxId", "TaxId", b1 =>
                        {
                            b1.Property<int>("Id")
                                .HasColumnType("int")
                                .HasColumnName("id");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("longtext")
                                .HasColumnName("tax_id");

                            b1.HasKey("Id")
                                .HasName("p_k_producers");

                            b1.ToTable("producers");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("f_k_producers_producers_id");
                        });

                    b.Navigation("ContactInfo")
                        .IsRequired();

                    b.Navigation("Location")
                        .IsRequired();

                    b.Navigation("ProductionInfo")
                        .IsRequired();

                    b.Navigation("TaxId")
                        .IsRequired();
                });

            modelBuilder.Entity("DevelopersTeam.Fruitlogix.Platform.OrderManagement.Domain.Model.Aggregates.Order", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
