// <auto-generated />
using System;
using DevelopersTeam.Fruitlogix.Platform.Shared.Infrastructure.Persistence.EFC.Configuration;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DevelopersTeam.Fruitlogix.Platform.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260605010448_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("DevelopersTeam.Fruitlogix.Platform.OrderManagement.Domain.Model.Aggregates.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("CancellationReason")
                        .HasColumnType("longtext")
                        .HasColumnName("cancellation_reason");

                    b.Property<int>("CommercialClientId")
                        .HasColumnType("int")
                        .HasColumnName("commercial_client_id");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<DateOnly>("DeliveryDueDate")
                        .HasColumnType("date")
                        .HasColumnName("delivery_due_date");

                    b.Property<string>("FruitType")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("fruit_type");

                    b.Property<string>("Notes")
                        .HasColumnType("longtext")
                        .HasColumnName("notes");

                    b.Property<int?>("ProducerId")
                        .HasColumnType("int")
                        .HasColumnName("producer_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("status");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("total_amount");

                    b.Property<double>("TotalVolume")
                        .HasColumnType("double")
                        .HasColumnName("total_volume");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_orders");

                    b.ToTable("orders");
                });

            modelBuilder.Entity("DevelopersTeam.Fruitlogix.Platform.OrderManagement.Domain.Model.Entities.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<string>("FruitName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("fruit_name");

                    b.Property<int?>("OrderId")
                        .HasColumnType("int")
                        .HasColumnName("order_id");

                    b.Property<double>("QuantityKg")
                        .HasColumnType("double")
                        .HasColumnName("quantity_kg");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("unit_price");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_order_items");

                    b.HasIndex("OrderId")
                        .HasDatabaseName("i_x_order_items_order_id");

                    b.ToTable("order_items");
                });

            modelBuilder.Entity("DevelopersTeam.Fruitlogix.Platform.OrderManagement.Domain.Model.Entities.OrderItem", b =>
                {
                    b.HasOne("DevelopersTeam.Fruitlogix.Platform.OrderManagement.Domain.Model.Aggregates.Order", null)
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("f_k_order_items_orders_order_id");
                });

            modelBuilder.Entity("DevelopersTeam.Fruitlogix.Platform.OrderManagement.Domain.Model.Aggregates.Order", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
